# Generated by Django 4.2.6 on 2024-02-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='developer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='username',
        ),
    ]
