# Generated by Django 4.2.6 on 2024-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Nigeria', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Lagos', max_length=30),
        ),
    ]
